apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: game-tls-cert
  dnsNames:
  - game.kubesight.online